[package]
name = "paragraph-breaker"
description = "An implementation of the Knuth-Plass algorithm for breaking paragraphs into lines"
repository = "https://github.com/baskerville/paragraph-breaker"
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
version = "0.4.3"
license = "MIT"
